# .github/workflows/deploy-sanity.yml
name: Build & Deploy Sanity to Cloud Run

on:
  push:
    branches: [ main ]

permissions:
  contents: 'read'      # for checkout
  id-token: 'write'     # required by auth@v2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        # no export_default_credentials here!

    - name: Build & Push Docker image
      run: |
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sanity-repo/sanity-studio:${{ github.sha }}"
        docker build -t $IMAGE ./sanity
        docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sanity-repo/sanity-studio:${{ github.sha }}"
        gcloud run deploy sanity-studio \
          --image $IMAGE \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars SANITY_PROJECT_ID=${{ secrets.SANITY_PROJECT_ID }},SANITY_DATASET=${{ secrets.SANITY_DATASET }}
