name: Build & Deploy Sanity to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud & Docker creds
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Build container image
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sanity-repo/sanity-studio:${{ github.sha }}"
          docker build -t $IMAGE ./sanity

      - name: Push to Artifact Registry
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sanity-repo/sanity-studio:${{ github.sha }}"
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sanity-repo/sanity-studio:${{ github.sha }}"
          gcloud run deploy sanity-studio \
            --image $IMAGE \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars SANITY_PROJECT_ID=${{ secrets.SANITY_PROJECT_ID }},SANITY_DATASET=${{ secrets.SANITY_DATASET }}
